'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailMaster
    Public Property id As Integer
    Public Property Address As String
    Public Property SPC_CAR_RPT As Boolean
    Public Property MCS_CAR_RPT As Boolean
    Public Property SPC_STT_RPT As Boolean
    Public Property ADMIN As Boolean
    Public Property INS_ALERT_EMAIL As Nullable(Of Boolean)
    Public Property SPEC_ALERT_EMAIL As Nullable(Of Boolean)
    Public Property HomeLocation As String

End Class
Partial Public Class LinkedServerMaster
    Public Property id As Integer
    Public Property DSN_Type As String
    Public Property DSN_Identifier As String
    Public Property LocationId As Integer
    Public Property LinkedServerName As String

    Public Overridable Property LocationMaster As LocationMaster

End Class
Partial Public Class LocationMaster
    Public Property id As Integer
    Public Property Name As String
    Public Property Abreviation As String
    Public Property DBname As String
    Public Property CID As String
    Public Property ConnectionString As String
    Public Property InspectionResults As Nullable(Of Boolean)
    Public Property ProductionResults As Nullable(Of Boolean)
    Public Property AS400_Connection As Nullable(Of Boolean)
    Public Property AS400_Abr As String

    Public Overridable Property LinkedServerMasters As ICollection(Of LinkedServerMaster) = New HashSet(Of LinkedServerMaster)
    Public Overridable Property OPCMasters As ICollection(Of OPCMaster) = New HashSet(Of OPCMaster)

End Class
Partial Public Class OPCMaster
    Public Property Id As Integer
    Public Property Name As String
    Public Property IPaddress As String
    Public Property LocationId As Integer

    Public Overridable Property LocationMaster As LocationMaster

End Class
Partial Public Class SPC_ApplicationLog
    Public Property id As Integer
    Public Property date_added As Date
    Public Property type As String
    Public Property Target As String
    Public Property Message As String
    Public Property application_name As String
    Public Property UserPK As Nullable(Of Integer)
    Public Property Error_Number As Nullable(Of Integer)

End Class
Partial Public Class UserActivityLog
    Public Property id As Integer
    Public Property DBOrigin As String
    Public Property UserID As String
    Public Property EntryTimestamp As Date
    Public Property DeviceType As String
    Public Property IPAddress As String
    Public Property CID As String
    Public Property ActivityType As String

    Public Overridable Property UserCrudActivityLogs As ICollection(Of UserCrudActivityLog) = New HashSet(Of UserCrudActivityLog)

End Class
Partial Public Class UserCrudActivityLog
    Public Property Id As Integer
    Public Property oper As String
    Public Property UserActivityLogId As Integer
    Public Property Timestamp As Date
    Public Property OriginalObject As String
    Public Property FinalObject As String
    Public Property DataBase As String
    Public Property Table As String
    Public Property PrimaryKeyTarget As Integer

    Public Overridable Property UserActivityLog As UserActivityLog

End Class
Partial Public Class SearchAllTables_Result
    Public Property ColumnName As String
    Public Property ColumnValue As String

End Class
Partial Public Class SP_SPC_GetTemplateLocationStatus_Result
    Public Property id As Integer
    Public Property Abr As String
    Public Property Name As String
    Public Property Status As Boolean

End Class
