'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Inspection_Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Inspection_Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ButtonLibraries() As DbSet(Of ButtonLibrary)
    Public Overridable Property ButtonTemplates() As DbSet(Of ButtonTemplate)
    Public Overridable Property DefectMasters() As DbSet(Of DefectMaster)
    Public Overridable Property DefectTimers() As DbSet(Of DefectTimer)
    Public Overridable Property EmployeeNoes() As DbSet(Of EmployeeNo)
    Public Overridable Property InspectionCompliances() As DbSet(Of InspectionCompliance)
    Public Overridable Property InspectionJobSummaries() As DbSet(Of InspectionJobSummary)
    Public Overridable Property InspectionTypes() As DbSet(Of InspectionType)
    Public Overridable Property Locations() As DbSet(Of Location)
    Public Overridable Property ProductSpecifications() As DbSet(Of ProductSpecification)
    Public Overridable Property RollInspectionDetails() As DbSet(Of RollInspectionDetail)
    Public Overridable Property RollInspectionSummaries() As DbSet(Of RollInspectionSummary)
    Public Overridable Property SpecMeasurements() As DbSet(Of SpecMeasurement)
    Public Overridable Property TabTemplates() As DbSet(Of TabTemplate)
    Public Overridable Property TemplateActivators() As DbSet(Of TemplateActivator)
    Public Overridable Property TemplateNames() As DbSet(Of TemplateName)
    Public Overridable Property WeaverProductions() As DbSet(Of WeaverProduction)
    Public Overridable Property WeaverShifts() As DbSet(Of WeaverShift)
    Public Overridable Property WorkRooms() As DbSet(Of WorkRoom)

End Class
