'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class Inspection_Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Inspection_Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ButtonLibraries() As DbSet(Of ButtonLibrary)
    Public Overridable Property ButtonTemplates() As DbSet(Of ButtonTemplate)
    Public Overridable Property DefectMasters() As DbSet(Of DefectMaster)
    Public Overridable Property DefectTimers() As DbSet(Of DefectTimer)
    Public Overridable Property InspectionJobSummaries() As DbSet(Of InspectionJobSummary)
    Public Overridable Property InspectionTypes() As DbSet(Of InspectionType)
    Public Overridable Property ProductSpecifications() As DbSet(Of ProductSpecification)
    Public Overridable Property RollInspectionDetails() As DbSet(Of RollInspectionDetail)
    Public Overridable Property RollInspectionSummaries() As DbSet(Of RollInspectionSummary)
    Public Overridable Property SpecMeasurements() As DbSet(Of SpecMeasurement)
    Public Overridable Property TabTemplates() As DbSet(Of TabTemplate)
    Public Overridable Property TemplateActivators() As DbSet(Of TemplateActivator)
    Public Overridable Property TemplateNames() As DbSet(Of TemplateName)
    Public Overridable Property INS_Summary_VW() As DbSet(Of INS_Summary_VW)
    Public Overridable Property LocationMaster_VW() As DbSet(Of LocationMaster_VW)
    Public Overridable Property STT_VW() As DbSet(Of STT_VW)
    Public Overridable Property EmployeeNoes() As DbSet(Of EmployeeNo)
    Public Overridable Property WeaverProductions() As DbSet(Of WeaverProduction)
    Public Overridable Property WeaverShifts() As DbSet(Of WeaverShift)

    Public Overridable Function SP_AS400_GETPRPCode_Ent(dATANO As String) As ObjectResult(Of String)
        Dim dATANOParameter As ObjectParameter = If(dATANO IsNot Nothing, New ObjectParameter("DATANO", dATANO), New ObjectParameter("DATANO", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("SP_AS400_GETPRPCode_Ent", dATANOParameter)
    End Function

End Class
